name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

        stack-yaml:
          - stack.yaml

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
 